SVD of the unspecified ratings. Predicting the ratings using surprise package. 

In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import svd
from surprise.model_selection import train_test_split
from surprise import Reader
from surprise import Dataset
from surprise import SVD, accuracy

In [2]:
d= {'Item ID 1': [5,4,'null',7,1],
    'Item ID 2': [6,'null',3,4,'null'], 
    'Item ID 3': [7,5,4,3,3], 
    'Item ID 4': [4,'null',1,6,2], 
    'Item ID 5': [3,5,1,'null',2], 
    'Item ID 6': ['null',4,'null',4,5] }

In [3]:
df = pd.DataFrame(data= d)

In [4]:
df

Item ID 1 Item ID 2  Item ID 3 Item ID 4 Item ID 5 Item ID 6
0         5         6          7         4         3      null
1         4      null          5      null         5         4
2      null         3          4         1         1      null
3         7         4          3         6      null         4
4         1      null          3         2         2         5

In [5]:
df['Item ID 1'] = df['Item ID 1'].replace({'null':np.nan}).astype(float)
df['Item ID 2'] = df['Item ID 2'].replace({'null':np.nan}).astype(float)
df['Item ID 4'] = df['Item ID 4'].replace({'null':np.nan}).astype(float)
df['Item ID 5'] = df['Item ID 5'].replace({'null':np.nan}).astype(float)
df['Item ID 6'] = df['Item ID 6'].replace({'null':np.nan}).astype(float)

In [6]:
df["Item ID 1"] = df["Item ID 1"].fillna(value=df["Item ID 1"].mean())
df["Item ID 2"] = df["Item ID 2"].fillna(value=df["Item ID 2"].mean())
df["Item ID 4"] = df["Item ID 4"].fillna(value=df["Item ID 4"].mean())
df["Item ID 5"] = df["Item ID 5"].fillna(value=df["Item ID 5"].mean())
df["Item ID 6"] = df["Item ID 6"].fillna(value=df["Item ID 6"].mean())

In [7]:
transposed_df = df.T
df.astype(float)
transposed_df.astype(float)

0         1         2     3         4
Item ID 1  5.000000  4.000000  4.250000  7.00  1.000000
Item ID 2  6.000000  4.333333  3.000000  4.00  4.333333
Item ID 3  7.000000  5.000000  4.000000  3.00  3.000000
Item ID 4  4.000000  3.250000  1.000000  6.00  2.000000
Item ID 5  3.000000  5.000000  1.000000  2.75  2.000000
Item ID 6  4.333333  4.000000  4.333333  4.00  5.000000

In [8]:
U, s, VT = svd(df)

In [9]:
U

array([[-0.55663663, -0.18323679,  0.02709014, -0.48610595, -0.64772453],
       [-0.46872406, -0.13250022, -0.61222162, -0.22256146,  0.58171516],
       [-0.34403602, -0.15424226,  0.78859143, -0.12826336,  0.46853026],
       [-0.49601448,  0.79411245,  0.02865913,  0.34546567, -0.05645506],
       [-0.32567203, -0.54264418, -0.04186899,  0.760506  , -0.13911373]])

In [10]:
s

array([22.00948622,  4.63341415,  2.88836178,  2.63051398,  1.77492629])

In [11]:
VT

array([[-0.45062414, -0.44518844, -0.45804251, -0.35081994, -0.2895547 ,
        -0.42664463],
       [ 0.62900238, -0.28301452, -0.39014921,  0.50968274, -0.05782623,
        -0.33003335],
       [ 0.4143604 , -0.06628012,  0.08422042, -0.34779281, -0.76035199,
         0.34310981],
       [-0.26121481,  0.15644467, -0.65032439,  0.3032845 , -0.08680658,
         0.62036538],
       [ 0.30716342, -0.44432107, -0.19047624, -0.47818967,  0.56365922,
         0.35436018],
       [ 0.25887604,  0.70386137, -0.41434836, -0.41897755,  0.09711828,
        -0.28443568]])

In [12]:
a = [0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,3,4,4,4,4,4]
b = [0,1,2,3,4,0,2,4,5,1,2,3,4,0,1,2,3,5,0,2,3,4,5]
c = [5,6,7,4,3,4,5,5,4,3,4,1,1,7,4,3,6,4,1,3,2,2,5]
new_data = pd.DataFrame({"uid": a,
    "iid": b, 
    "rating": c })

In [13]:
new_data

uid  iid  rating
0     0    0       5
1     0    1       6
2     0    2       7
3     0    3       4
4     0    4       3
5     1    0       4
6     1    2       5
7     1    4       5
8     1    5       4
9     2    1       3
10    2    2       4
11    2    3       1
12    2    4       1
13    3    0       7
14    3    1       4
15    3    2       3
16    3    3       6
17    3    5       4
18    4    0       1
19    4    2       3
20    4    3       2
21    4    4       2
22    4    5       5

In [14]:
reader = Reader(rating_scale=(1., 10.))

In [15]:
da = Dataset.load_from_df(new_data,reader)

Expected rating for user 1 and item 4:

In [16]:
algo = SVD()
algo.fit(da.build_full_trainset())
pred = (algo.predict(uid =1 ,iid =3)).est
pred

3.7082600690666454

Expected rating for user 1 and item 2:

In [17]:
algo = SVD()
algo.fit(da.build_full_trainset())
pred = (algo.predict(uid =1 ,iid =1)).est
pred

4.316214616207893